<?php

/**
 * @file
 * Contains phpunit_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function phpunit_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the phpunit_example module.
    case 'help.page.phpunit_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My first PHPUnit test') . '</p>';
      return $output;

    default:
  }
}
